### ISSUE TITLE
Impossible de désactiver un équipement si non connecté au réseau wifi

### ISSUE THREAD

**Issue by Gis70** [NextDom/NotiFHeure#3]
## Etapes à reproduire (pour les bugs)

1. Désactiver un équipement non connecté au réseau
2. retour de Jeedom : L'adresse 192.168.0.49 ne semble pas joignable - Merci de verifier cette adresse.
3. L'équipement n'est donc pas désactivé
4.

## Environnement:
Debian 9
* **Version Jeedom**: 3.3.16
* **Plateforme**: NUC VM
* **Version du Plugin**: Dernière en stable

**Comment by byfeel** [comment]
Merci pour le retour.
Je viens de corriger le bug  sur la version 1.1.2
