### ISSUE TITLE
Warning about division by Zero

### ISSUE THREAD

**Issue by psycofdj** [NextDom/NotiFHeure#4]
**Describe the bug**

Object construction produces multiple `Division by zero` warnings in `core/class/NotifHeure.class.php`

https://github.com/NextDom/plugin-NotifHeure/blob/4fe9536f07479e2e4d78fbc32c873ccbc2876669/core/class/NotifHeure.class.php#L54-L66

**Comment by frederic34** [comment]
need to keep one value true or false, true divided by false give error
replace every true/false by only true or false

https://jeedom.github.io/plugin-template/fr_FR/

**Comment by byfeel** [comment]
ok . 
update fix bug V1.1.3
